# Generated by Django 3.2 on 2022-02-19 07:14

from django.db import migrations

def copy_price_to_order_item(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')
    products = Product.objects.all()
    order_items = OrderItem.objects.all()
    for item in order_items.iterator():
        OrderItem.objects.update_or_create(id=item.id, defaults={
            'price': products.get(id=item.product.id).price
        })

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_order_item),
    ]
