# Generated by Django 3.2 on 2022-02-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20220219_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(choices=[(True, 'Обработанный'), (False, 'Необработанный')], db_index=True, default=False, verbose_name='обработан'),
        ),
    ]
