# Generated by Django 3.2 on 2022-02-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220214_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'пункт заказа', 'verbose_name_plural': 'пункты заказа'},
        ),
    ]
