# Generated by Django 3.2 on 2022-02-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
