# Generated by Django 3.2 on 2022-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(to='foodcartapp.Restaurant', verbose_name='рестораны'),
        ),
    ]
