# Generated by Django 3.2 on 2022-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_rename_phone_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='обработан'),
            preserve_default=False,
        ),
    ]
