# Generated by Django 3.2 on 2022-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(related_name='orders', to='foodcartapp.Restaurant', verbose_name='рестораны'),
        ),
    ]
