# Generated by Django 3.2 on 2022-03-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurants',
        ),
    ]
