# Generated by Django 3.2 on 2022-03-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_remove_order_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
